apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql1
spec:
  containers:
  - name: mysqlcontainer
    image: 021539915150.dkr.ecr.us-east-1.amazonaws.com/harshclo835-repository-mysql:v1.0
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: harsh123
    - name: MYSQL_DATABASE
      value: employees
  