apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: appreplicaset
  namespace: webapp
  labels:
      app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employee-myapp
        image: 021539915150.dkr.ecr.us-east-1.amazonaws.com/harshclo835-webapp:v1.0
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: "sqlservice.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "harsh123"
        - name: APP_COLOR
          value: "lime"  
        - name: DATABASE
          value: "employees"
          
