name: Deploy to ECR

on: 
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v2

   
